import {MyTheme} from '@utils';
import {StyleSheet, Dimensions} from 'react-native';
const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;
export const styles = StyleSheet.create({
  verifyOtpContainer: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: MyTheme.white,
  },
  verifyOtpHeader: {
    width: '100%',
    flexDirection: 'row',
    width: width - 40,
    height: 21,
    marginTop: 18,
    alignItems: 'center',
  },
  verifyOtpHeaderText: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 16,
    lineHeight: 21,
    color: MyTheme.black,
    marginLeft: 11,
  },
  verifyOtpBtn: {
    height: 56,
    width: width - 40,
    marginTop: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 69,
    backgroundColor: MyTheme.primary,
    color: MyTheme.textPrimary,
  },
  notVerifyOtpBtn: {
    height: 56,
    width: width - 40,
    marginTop: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 69,
    color: MyTheme.textPrimary,
    backgroundColor: MyTheme.grey300,
  },
  verifyOtpText: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    color: MyTheme.textPrimary,
  },
  notVerifyOtpText: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    color: MyTheme.textPrimary,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    backgroundColor: '#00000080',
  },
  modalView: {
    width: width - 50,
    height: 245,
    backgroundColor: MyTheme.primary,
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonClose: {
    height: 3,
    width: 53,
    marginTop: 15,
    backgroundColor: MyTheme.grey200,
  },
  modalText: {
    width: '100%',
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 20,
    color: MyTheme.black,
    marginTop: 17,
    marginLeft: 24,
  },
  successContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: MyTheme.primary,
    borderRadius: 10,
  },
  successImage: {
    width: 85,
    height: 70,
    marginTop: 20,
    borderRadius: 10,
  },
  successText: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: 16,
    lineHeight: 25,
    color: MyTheme.black,
    marginTop: 17,
  },
  successMessage: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 12,
    lineHeight: 20,
    color: MyTheme.black,
    marginTop: 7,
  },
  okPres: {
    width: width - 91,
    height: 56,
    marginTop: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 69,
    backgroundColor: MyTheme.accent,
  },
  okPresText: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    color: MyTheme.white,
  },
});
