export const vendorUris = {
  login: 'api/vendor/login',
  verifyVendor: 'api/vendor/verify-vendor',
  logout: 'api/vendor/logout',
  orderHistory: 'api/vendor/order-history',
  vendorProfile: 'api/vendor/user',
  verifyOtp: 'api/vendor/verify/otp',
  forgotPasswordRequest: 'api/vendor/forgot-password-request',
  resetPassword: 'api/vendor/reset-password',
  updateProfileImage: 'api/vendor/update-profile-image',
  createOrder: 'api/vendor/create-order',
  userVerifyUser: 'api/vendor/verify-user',
  userSendOtpCode: 'api/vendor/send-otpcode',
  userVerifyOtpCode: 'api/vendor/verify-otpcode',
  promotionCreate: 'api/vendor/promotion/create',
  promotionListing: 'api/vendor/promotion/listing',
  promotionFindById: 'api/vendor/promotion/findById/3',
  promotionDelete: 'api/vendor/promotion/delete/',
  promotionUpdate: 'api/vendor/promotion/update/',
  updateProfileImage: 'api/customer/update-profile-image',
  updatePassword: 'api/vendor/update-password',
};
