import {MyTheme} from '@utils';
import {StyleSheet, Dimensions} from 'react-native';
const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;
export const styles = StyleSheet.create({
  dashboardContainer: {
    flex: 1,
    // justifyContent:"center",
    alignItems: 'center',
    // justifyContent:"center",
    backgroundColor: 'white',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: width - 30,
    marginTop: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MyTheme.grey200,

    shadowColor: '#000',
    shadowOffset: {
      width: -2,
      height: 1,
    },
    shadowOpacity: 0.52,
    shadowRadius: 2.22,

    elevation: -2,
  },
  searchPress: {
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchImage: {
    width: 14,
    height: 14,
    marginRight: 15.5,
  },
  searchInput: {
    width: '80%',
    paddingLeft: 16,
  },
  vendors: {
    marginTop: 23,
    width: '100%',
    height: 100,
    // alignItems: 'center',
  },
  ads: {
    marginTop: 25,
    width: '100%',
    height: 140,
    // alignItems: 'center',
  },
  heading: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: 16,
    // lineHeight: 21,
    color: MyTheme.textPrimary,
  },
  description: {
    fontFamily: MyTheme.poppins,
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 12,
    // lineHeight: 21,
    color: MyTheme.textPrimary,
  },
  headingVendor: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 12,
    lineHeight: 18,
    color: MyTheme.textPrimary,
    marginLeft: 16,
    alignContent: 'center',
  },

  imageView: {
    width: '30%',
    height: 105,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    // borderBottomWidth: 1,
    borderColor: MyTheme.grey200,
    borderRadius: 8,
    backgroundColor: MyTheme.primary,
  },
  cardImage: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
  },
  notificationHeader: {
    width: '100%',
    flexDirection: 'row',
    position: 'absolute',
    width: width - 40,
    height: 25,
    top: 70,
  },
  notificationHeaderText: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 24,
    lineHeight: 20,
    color: MyTheme.textPrimary,
    paddingTop: 5,
    marginLeft: 5,
  },
  btns: {
    marginTop: '7%',
    width: width - 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  btn: {
    backgroundColor: MyTheme.primary,
    width: 100,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2%',
    borderRadius: 8,
  },
  btnText: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 14,
    lineHeight: 20,
    color: MyTheme.textPrimary,
  },
});
