import {MyTheme} from '@utils';
import {StyleSheet, Dimensions} from 'react-native';
const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;
export const styles = StyleSheet.create({
  bottomBarContainer: {
    width: width - 18,
    height: 61,
    backgroundColor: MyTheme.dark,
    borderRadius: 70,
    position: 'absolute',
    bottom: 12,
    paddingHorizontal: 31.17,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  iconView: {
    width: 61.67,
    height: 40.93,
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    width: 21.67,
    height: 20.93,
  },
  iconText: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 11,
    lineHeight: 12,
    color: MyTheme.white,
    marginTop: 7,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // marginTop: 22,
    width: '100%',
    backgroundColor: '#00000080',
  },
  modalView: {
    // margin: 20,
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: height / 2.15,
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonClose: {
    height: 3,
    width: 53,
    marginTop: 15,
    backgroundColor: MyTheme.grey200,
  },
  modalText: {
    width: '100%',
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 20,
    color: MyTheme.black,
    marginTop: 17,
    marginLeft: 24,
  },
  categoriesView: {
    marginTop: 29,
    width: width,
    flexDirection: 'row',
    flexWrap: 'wrap',
    height: '100%',
  },
  category: {
    width: 80,
    marginHorizontal: 10,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryIconView: {
    width: 45,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: MyTheme.grey400,
    borderRadius: 40,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  categoryText: {
    fontFamily: MyTheme.fontFamily,
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 10,
    lineHeight: 14,
    color: MyTheme.black,
    marginTop: 6,
  },
  categoryIcon: {
    width: 22,
    height: 22,
  },
});
